### ISSUE TITLE
Poseidon Hash/RAMT/SMT

### ISSUE THREAD

**Issue by albertog78** [HorizenOfficial/zendoo-sc-cryptolib#14]
To be able to not have to collect first all the inputs together and then passing them to poseidon, expose via JNI the new implementation coming from ginger lib (https://github.com/ZencashOfficial/ginger-lib/issues/56)

**Comment by DanieleDiBenedetto** [comment]
It's needed to expose also the new MerkleTrees in branch https://github.com/HorizenOfficial/ginger-lib/tree/smt

**Comment by DanieleDiBenedetto** [comment]
Done and merged for UpdatablePoseidonHash and InMemoryOptimizedMHT.
