### ISSUE TITLE
Derive dlog keys size from snark pk when proving

### ISSUE THREAD

**Issue by DanieleDiBenedetto** [HorizenOfficial/zendoo-sc-cryptolib#85]
It should be possible (please @UlrichHaboeck75 confirm) to derive the dlog key size by reading index data and the number of commitments inside the snark pk passed to prover. In this way, we wouldn't need to pass the supported segment size to the prover functions, thus reducing the possibility of introducing bugs.
If not possible, or if there is a more elegant way to do it, let's discuss on alternatives

**Comment by UlrichHaboeck75** [comment]
As discussed offline, it's not possible to uniquely determine the segment size from the pk including the size of domain H and K.
